### ISSUE TITLE
(De)serialize `State` property when using `TaskEntity<TState>`-based implementation not working (correctly)

### ISSUE THREAD

**Issue by Fazer01** [microsoft/durabletask-dotnet#280] opened 2024-04-03 12:26 UTC
Hi there, 

Following the [docs](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-entities?pivots=isolated#defining-entity-classes) and using the `TaskEntity<TState>` implementation, `state` is the only property that is serialized/deserialized. Actually, it's not as is seems... (or I'm missing something perhaps). Using the latest package `Microsoft.DurableTask.Abstractions (1.2.2)` via `Microsoft.Azure.Functions.Worker.Extensions.DurableTask (1.1.2)` package

Example of the `Counter` entity as stated by the mentioned docs: 
```csharp
public class Counter : TaskEntity<int>
{
    readonly ILogger logger; 

    public Counter(ILogger<Counter> logger)
    {
        this.logger = logger; 
    }

    public void Add(int amount) 
    {
        this.State += amount;
    }

    public Task Reset() 
    {
        this.State = 0;
        return Task.CompletedTask;
    }

    public Task<int> Get() 
    {
        return Task.FromResult(this.State);
    }

    // Delete is implicitly defined when defining an entity this way

    [Function(nameof(Counter))]
    public static Task Run([EntityTrigger] TaskEntityDispatcher dispatcher)
        => dispatcher.DispatchAsync<Counter>();
}
```

Small test where `serializedNewCounter` does not contain any property: 
```csharp
var newCounter = new Counter(NullLoggerFactory.Instance.CreateLogger<Counter>());
newCounter.Reset();
newCounter.Add(3);

var serializedNewCounter = System.Text.Json.JsonSerializer.Serialize(newCounter);
```
![image](https://github.com/microsoft/durabletask-dotnet/assets/37348010/b7c155f1-e305-461b-82a7-e7a1121e4953)

### Expected: 
The `state` property serialized as mentioned in the docs...

**Comment by davidmrdavid** [comment] 2024-04-19 23:33
Hey @Fazer01: I'm unsure if the expectation is for application code to be serializing the entity itself, I believe the docs mean to say that the Durable Functions framework, when _it_ serializes the entity, we are durably preserving the `state` variable. Is there a reason why you're manually serializing it yourself?

cc/ @jviau who is familiar with this implementation

**Comment by Fazer01** [comment] 2024-04-22 10:39
Hi @davidmrdavid, 

Thanks for have a look into this. I was just having a look given a particular Durable Entity (in my case the Counter entity) and serialize it by myself, I'd expect to have a certain state serialized with it when using a simple test like above. 

However, when the durable entity is used by our application's code, and let the DFx serialize the Durable Entity, the `state` property is serialized correclty as well.

**Comment by jviau** [comment] 2024-04-22 22:07
@Fazer01 the behavior you see is by design. The state property is the only one serialized, not because we are serializing the entire entity, but because we explicitly capture the state property at the end of the entity invocation:

https://github.com/microsoft/durabletask-dotnet/blob/main/src/Abstractions/Entities/TaskEntityHelpers.cs#L49

Closing this as by design.

**Closed by jviau** 2024-04-22 22:07 UTC
Labels: documentation, P2

**Comment by Fazer01** [comment] 2024-04-23 08:45
@jviau and @davidmrdavid  Thanks for answering. Perhaps the docs could be clarified about this that no application code should be serializing the entity itself.

**Comment by jviau** [comment] 2024-04-23 15:41
> Perhaps the docs could be clarified about this that no application code should be serializing the entity itself.

I don't think that is accurate. There is nothing stopping you from making a custom serialization handler for the serialization library you are using which will serialize only state. But that is outside of the scope of this framework. The docs are accurate, and I don't really want to get into implementation details (which this is) in the docs as those can change.

**Comment by davidmrdavid** [comment] 2024-04-23 15:44
@Fazer01 - just out of curiosity - can you paste what documentation blurb you think should be updated? Is there a particular section of the docs that you think is confusing? That would help, thanks.

**Comment by Fazer01** [comment] 2024-04-24 08:34
@davidmrdavid Perhaps here?
![image](https://github.com/microsoft/durabletask-dotnet/assets/37348010/6784e80c-af31-4b67-80b9-f65561e9cafb)

But actually, with the knowledge you and @jviau gave me, it's understandable. 

I was just curious about how the framework handles this. Maybe I should have asked a question instead of the `state` property not being serialized correctly (when serializing from application code). 

Anyway, thanks for elaborating on this gents! Have a nice day!
