### ISSUE TITLE
Class syntax example doesn't work

### ISSUE THREAD

**Issue by kaibocai** [microsoft/durabletask-dotnet#269] opened 2024-02-23 02:32 UTC
I am playing with the class syntax example at https://github.com/microsoft/durabletask-dotnet/blob/main/samples/AzureFunctionsApp/HelloCitiesTyped.cs,

I clone the sample code and try to run it on my local, but get exceptions as 

```[2024-02-23T02:21:22.656Z] Function 'StartHelloCitiesTyped', Invocation id '3bc9da66-ad29-4624-a091-c01983e115e5': An exception was thrown by the invocation.
[2024-02-23T02:21:22.657Z] Result: Function 'StartHelloCitiesTyped', Invocation id '3bc9da66-ad29-4624-a091-c01983e115e5': An exception was thrown by the invocation.
Exception: System.AggregateException: One or more errors occurred. (Status(StatusCode="Unknown", Detail="Exception was thrown by handler."))
[2024-02-23T02:21:22.658Z]  ---> Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
[2024-02-23T02:21:22.659Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableTaskClient.ScheduleNewOrchestrationInstanceAsync(TaskName orchestratorName, Object input, StartOrchestrationOptions options, CancellationToken cancellation)
[2024-02-23T02:21:22.661Z]    at AzureFunctionsApp.Typed.HelloCitiesTypedStarter.StartHelloCitiesTyped(HttpRequestData req, DurableTaskClient client, FunctionContext executionContext) in D:\code\dapr\dtmb\durabletask-dotnet\samples\AzureFunctionsApp\HelloCitiesTyped.cs:line 34
[2024-02-23T02:21:22.662Z]    --- End of inner exception stack trace ---
[2024-02-23T02:21:22.663Z]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2024-02-23T02:21:22.663Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2024-02-23T02:21:22.664Z]    at System.Threading.Tasks.Task`1.get_Result()
[2024-02-23T02:21:22.665Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2024-02-23T02:21:22.667Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2024-02-23T02:21:22.668Z]    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
[2024-02-23T02:21:22.669Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2024-02-23T02:21:22.670Z] --- End of stack trace from previous location ---
[2024-02-23T02:21:22.673Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2024-02-23T02:21:22.675Z] --- End of stack trace from previous location ---
[2024-02-23T02:21:22.675Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
[2024-02-23T02:21:22.677Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-02-23T02:21:22.678Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
Stack:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2024-02-23T02:21:22.679Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2024-02-23T02:21:22.680Z]    at System.Threading.Tasks.Task`1.get_Result()
[2024-02-23T02:21:22.681Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2024-02-23T02:21:22.682Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2024-02-23T02:21:22.683Z]    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
[2024-02-23T02:21:22.684Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2024-02-23T02:21:22.685Z] --- End of stack trace from previous location ---
[2024-02-23T02:21:22.687Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2024-02-23T02:21:22.690Z] --- End of stack trace from previous location ---
[2024-02-23T02:21:22.691Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
[2024-02-23T02:21:22.692Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-02-23T02:21:22.693Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77.
[2024-02-23T02:21:22.725Z] Executed 'Functions.StartHelloCitiesTyped' (Failed, Id=3bc9da66-ad29-4624-a091-c01983e115e5, Duration=304ms)
[2024-02-23T02:21:22.726Z] System.Private.CoreLib: Exception while executing function: Functions.StartHelloCitiesTyped. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (Status(StatusCode="Unknown", Detail="Exception was thrown by handler."))
[2024-02-23T02:21:22.727Z]  ---> Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
[2024-02-23T02:21:22.729Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableTaskClient.ScheduleNewOrchestrationInstanceAsync(TaskName orchestratorName, Object input, StartOrchestrationOptions options, CancellationToken cancellation)
[2024-02-23T02:21:22.730Z]    at AzureFunctionsApp.Typed.HelloCitiesTypedStarter.StartHelloCitiesTyped(HttpRequestData req, DurableTaskClient client, FunctionContext executionContext) in D:\code\dapr\dtmb\durabletask-dotnet\samples\AzureFunctionsApp\HelloCitiesTyped.cs:line 34
[2024-02-23T02:21:22.731Z]    --- End of inner exception stack trace ---
[2024-02-23T02:21:22.732Z]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2024-02-23T02:21:22.733Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2024-02-23T02:21:22.737Z]    at System.Threading.Tasks.Task`1.get_Result()
[2024-02-23T02:21:22.738Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2024-02-23T02:21:22.739Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2024-02-23T02:21:22.740Z]    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
[2024-02-23T02:21:22.741Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2024-02-23T02:21:22.742Z] --- End of stack trace from previous location ---
[2024-02-23T02:21:22.743Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2024-02-23T02:21:22.744Z] --- End of stack trace from previous location ---
[2024-02-23T02:21:22.745Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
[2024-02-23T02:21:22.746Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-02-23T02:21:22.748Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
[2024-02-23T02:21:22.751Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
Stack:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2024-02-23T02:21:22.754Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2024-02-23T02:21:22.755Z]    at System.Threading.Tasks.Task`1.get_Result()
[2024-02-23T02:21:22.756Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2024-02-23T02:21:22.758Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2024-02-23T02:21:22.758Z]    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
[2024-02-23T02:21:22.759Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2024-02-23T02:21:22.760Z] --- End of stack trace from previous location ---
[2024-02-23T02:21:22.761Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2024-02-23T02:21:22.762Z] --- End of stack trace from previous location ---
[2024-02-23T02:21:22.763Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
[2024-02-23T02:21:22.766Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-02-23T02:21:22.768Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
[2024-02-23T02:21:22.770Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88.
```

**Comment by kaibocai** [comment] 2024-02-23 02:41
Workaround: define version of your dependency as 
```  
<ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.14.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.0.2" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.10.0" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.DurableTask.Generators" Version="1.0.0-preview.1" OutputItemType="Analyzer" />
  </ItemGroup>
```

**Comment by jviau** [comment] 2024-04-01 17:02
Duplicate of #247

**Closed by jviau** 2024-04-01 17:02 UTC
Labels: bug, P1
