### ISSUE TITLE
Typed input for Orchestrator is not deserializing properly. FunctionsOrchestrationContext.JsonElementInputConverter  is case sensitive on Deserialization

### ISSUE THREAD

**Issue by ulvesked** [microsoft/durabletask-dotnet#234] opened 2023-11-01 10:25 UTC
Microsoft.Azure.Functions.Worker.Extensions.DurableTask.ObjectConverterShim serializes with camelCase. 
However it is case sensitive when deserializing, so the values will end up with defaults.

```
public class MyOrchestratorParameters
{
    public DateTime FromDate { get; set; }
    public DateTime ToDate { get; set; }
}
```
will be serialized to 
```
{"fromDate":"2023-07-01T00:00:00","toDate":"2023-11-01T00:00:00"}
```

The input to my orchestrator is then initialized with default values (DateTime.MinValue) for both FromDate and EndDate.

If I force serialization using PascalCase it works.

```
public class TripletexImportOrchestratorParameters
{
    [JsonPropertyName("FromDate")]
    public DateTime FromDate { get; set; }
    [JsonPropertyName("ToDate")]
    public DateTime ToDate { get; set; }
}
```
which will be serialized to 
```
{"FromDate":"2023-07-01T00:00:00","ToDate":"2023-11-01T00:00:00"}
```

---

It appears `FunctionsOrchestrationContext.JsonElementInputConverter` does not provide JsonSerializerOptions, and thus uses 
```
PropertyNameCaseInsensitive = false 
PropertyNamingPolicy = null
```

**Comment by jviau** [comment] 2023-11-02 21:47
`FunctionsOrchestrationContext.JsonElementInputConverter` options conversion can be configured via: `services.Configure<JsonSerializerOptions>(o => { ... });`. By default this will also configure the JsonConverter used for `ObjectConverterShim` (as `WorkerOptions.ObjectSerializer` will use it).

I was unable to reproduce your issue this way.

1. No serialization customization (all default): pascal case.
2. Adding `.ConfigureServices(s => s.Configure<JsonSerializerOptions>(o => o.PropertyNamingPolicy = JsonNamingPolicy.CamelCase))` to my main method, everything is camel case. Serialization works as expected.

Also by default in functions, `JsonSerializerOptions.PropertyNameCaseInsensitive` is `true`. Did you set this to `false` by chance?

**Comment by ulvesked** [comment] 2023-11-08 12:18
I have created a sample project which demonstrates the issue. 
With no serialization customization (all default) everything works.

When adding `.ConfigureServices(s => s.Configure<JsonSerializerOptions>(o => o.PropertyNamingPolicy = JsonNamingPolicy.CamelCase))` it breaks.

See repo: 
https://github.com/ulvesked/DurableTaskOrchestratorPayloadSerialization

**Comment by ulvesked** [comment] 2023-11-08 12:38
Here are some thing I have found: 

`FunctionsOrchestrationContext.JsonElementInputConverter.Get<T>()` calls Deserialize without options.

https://github.com/Azure/azure-functions-durable-extension/blob/9f750ebc77fda1f52c5042dcdb41e6eb52ee7fdb/src/Worker.Extensions.DurableTask/FunctionsOrchestrationContext.InputConverter.cs#L57

If no options are provided to Deserialize, `System.Text.Json.JsonSerializer.GetTypeInfo()` defaults to `JsonSerializerOptions.Default`

https://github.com/dotnet/runtime/blob/deb43368fde438b3e6928d3930f1362a4960fdf4/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Helpers.cs#L36C29-L36C54

**Comment by jviau** [comment] 2023-11-08 18:01
Thank you for identifying the version it is fixed in.

**Closed by jviau** 2023-11-08 18:01 UTC
Labels: needs: author response
