### ISSUE TITLE
Workflow errors don't show up in logs

### ISSUE THREAD

**Issue by nilsmehlhorn** [microsoft/durabletask-dotnet#191] opened 2023-09-18 07:02 UTC
We've recently migrated our durable functions project to the isolated worker setup. Now we noticed that we're missing certain errors, specifically ones occurring immediately inside durable orchestrators. Such workflow errors don't show up in local logs nor inside our application insights (errors from activities or regular functions do).

[Here](https://github.com/nilsmehlhorn/DurableFunctionLoggingRepro)'s a reproduction with different intentional error sources. The logging setup follows https://github.com/Azure/azure-functions-dotnet-worker/issues/1182 (or rather the latest [docs](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#application-insights)). The reproduction contains three different orchestrators which may be started via the Durable Functions Admin API.

- `OrchestratorWithFailingActivity`: an error is thrown inside `FailingActivity` which shows up properly in the logs
- `OrchestratorWithFailingWorkflow`: an error is thrown directly inside the orchestrator and does not show up in the logs
- `OrchestratorWithNonDeterministicWorkflow`: a `NonDeterministicOrchestrationException` is triggered by violation of the code constraints via a static variable, the error does not show up in the logs

All three orchestrators end up in the "Failed" runtime status and their output contains the corresponding error message.

The reproduction contains a partial workaround in the form of a `DurableTaskExceptionHandlingMiddleware` which intercepts orchestration invocations and logs an error for exceptions which don't originate from activities (based on `TaskFailedException` type). The middleware needs to be registered within `Program.cs`. Unfortunately, it does not handle the non-determinism exception - I assume because the verification for that occurs after the middleware is invoked.

**Comment by cgillum** [comment] 2023-09-19 20:47
Possibly related: https://github.com/microsoft/durabletask-dotnet/issues/140.

**Comment by jviau** [comment] 2023-11-01 21:58
I believe this is the same as https://github.com/Azure/azure-functions-durable-extension/issues/2595. Closing as a duplicate of that.

**Closed by jviau** 2023-11-01 21:58 UTC
Labels: bug, P1
