### ISSUE TITLE
Durable Task: Activity Exception thrown as an unhandled exception

### ISSUE THREAD

**Issue by GOB-Sinzinger** [microsoft/durabletask-dotnet#257] opened 2023-12-15 07:38 UTC
In our Azure Durable Functions, the problem occurs that exceptions thrown in an activity trigger occur as unhandled exceptions.

To concretize the problem, I have built the following example:

```
[Function(nameof(Function1))]
public static async Task RunOrchestrator(
    [OrchestrationTrigger] TaskOrchestrationContext context)
{
    ILogger logger = context.CreateReplaySafeLogger(nameof(Function1));

    try
    {
        await context.CallActivityAsync(nameof(ExceptionTest));
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Exception caught");
        throw;
    }
}

[Function(nameof(ExceptionTest))]
public static void ExceptionTest([ActivityTrigger] FunctionContext executionContext)
{
    ILogger logger = executionContext.GetLogger("SayHello");
    logger.LogInformation("Throw Exception");

    throw new Exception("Test Exception");
}
```

If the ExceptionTest is started and the exception is thrown, I get the following exception in the orchestration trigger.

> DurableTask.Core.Exceptions.OrchestrationFailureException: Task 'ExceptionTest' (#0) failed with an unhandled exception: Test Exception\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.RemoteOrchestratorContext.ThrowIfFailed() in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\ContextImplementations\\RemoteOrchestratorContext.cs:line 58\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.OutOfProcMiddleware.

However, the exception should not occur as an unhandled exception.

My project Parameters:
- .NET 8 Isolated
- Packages:
Microsoft.Azure.Functions.Worker - 1.20.0
Microsoft.Azure.Functions.Worker.Extensions.DurableTask - 1.1.0
Microsoft.Azure.Functions.Worker.Extensions.Http - 3.1.0
Microsoft.Azure.Functions.Worker.Sdk - 1.16.4
Microsoft.ApplicationInsights.WorkerService - 2.22.0
Microsoft.Azure.Functions.Worker.ApplicationInsights - 1.1.0

Reference:
@GOB-Sinzinger would you mind opening a new issue for the problem you're seeing? It seems like there may actually be multiple things discussed in this thread and I want to make sure we cover each issue independently, lest things get lost.

_Originally posted by @cgillum in https://github.com/microsoft/durabletask-dotnet/issues/140#issuecomment-1850595682_

**Comment by jviau** [comment] 2023-12-19 23:20
@GOB-Sinzinger not sure I understand your request. The sample code you shared is indeed an unhandled exception. You throw an exception from your activity, durable captures that and rethrows it in your orchestration. You catch it, but then re-throw via the `throw` keyword.

This is the definition of unhandled - your code is letting the exception escape.

**Comment by GOB-Sinzinger** [comment] 2024-01-03 10:55
@jviau Thanks for your answer.

You're right, I just re-throw the exception in my orchestrator, but how else can I catch the exception and pass it to the user's output?

As far as I know, the orchestrator is the highest level, I could handle exceptions in a durable function. 

I've tested with a middleware to handle the exception, but it doesn't show the expected behavior either.

My goal is to get a clean exception message in the output token of the status query. 

So it looks something like this:
```
"name": "Function1",
"runtimeStatus": "Failed",
"output": "[Actually exception message of the activity]"
```

The current behavior is this output:
`"output": "One or more errors occurred. (Task 'ExceptionTest' (#0) failed with an unhandled exception: Test Exception)"`

**Comment by jviau** [comment] 2024-01-24 22:07
Ah okay. Yeah the framework is dropping inner-exception details, which is what you want. This is a duplicate of #140 then.

**Closed by jviau** 2024-01-24 22:07 UTC
Labels: needs: investigation
