### ISSUE TITLE
Unable to cast object of type 'System.Text.Json.JsonElement' to type

### ISSUE THREAD

**Issue by smokedlinq** [microsoft/durabletask-dotnet#36] opened 2022-08-11 14:08 UTC
There appears to be a bug when a POCO is used as an input it doesn't appear to deserialize the object to the POCO and JsonElement is not castable to other types. I observed this same issue with both the traditional function methods and the class-based tasks.

Error: `One or more errors occurred. (Unable to cast object of type 'System.Text.Json.JsonElement' to type 'Microsoft.DurableTask.Person'.)`

Example:

```csharp
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.DurableTask;
using System;
using System.Threading;
using System.Threading.Tasks;

// POCO placed here because of https://github.com/microsoft/durabletask-dotnet/issues/35
namespace Microsoft.DurableTask
{
    public class Person
    {
        public string Name { get; set; }
    }

    public class Message
    {
        public string Value { get; set; }
    }
}

namespace FunctionApp1_DotnetIsolated
{
    public class Function1
    {
        [Function(nameof(Function1))]
        public async Task<HttpResponseData> RunAsync([HttpTrigger] HttpRequestData req, [DurableClient] DurableClientContext durableContext)
        {
            var person = BinaryData.FromStream(req.Body).ToObjectFromJson<Person>();
            var instanceId = await durableContext.Client.ScheduleNewOrchestrationInstanceAsync(nameof(SayHelloOrchestrator), input: person);
            var result = await durableContext.Client.WaitForInstanceCompletionAsync(instanceId, CancellationToken.None, getInputsAndOutputs: true).ConfigureAwait(false);

            var response = req.CreateResponse();
            await response.WriteAsJsonAsync(result.ReadOutputAs<Message>()).ConfigureAwait(false);

            return response;
        }
    }

    public class SayHelloOrchestrator
    {
        [Function(nameof(SayHelloOrchestrator))]
        public async Task<Message> RunAsync([OrchestrationTrigger] TaskOrchestrationContext context)
        {
            var person = context.GetInput<Person>();
            var message = await context.CallActivityAsync<Message>(nameof(GetMessageActivity), person);
            return message;
        }
    }

    public class GetMessageActivity
    {
        [Function(nameof(GetMessageActivity))]
        public Task<Message> RunAsync([ActivityTrigger] Person person)
        {
            var message = new Message { Value = $"Hello {person.Name}!" };
            return Task.FromResult(message);
        }
    }
}
```

Package references:

```xml
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="0.4.1-beta" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.4.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0-preview2" OutputItemType="Analyzer" />
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.8.0" />
```

**Comment by jviau** [comment] 2022-08-17 20:58
Thank you for the report. I believe this is already tracked via #34. You can find the cause there.

**Comment by cgillum** [comment] 2022-09-20 18:13
@jviau with your recent fix, are we able to close this issue?

**Comment by jviau** [comment] 2022-09-20 19:44
I want to verify this exact scenario first before I resolve this issue.

**Comment by Tyler-V** [comment] 2022-11-03 21:51
Just ran into this myself trying to switch from in-process to isolated - are the orchestrators unable to deserialize json objects?

![image](https://user-images.githubusercontent.com/3893234/199841353-5a41e2c4-8ac4-44e1-966c-7e3284e1bcc5.png)

```
public class FileUploadOrchestratorInput
{
    public int? DataFileId { get; set; }
    public string FileName { get; set; }
    public List<BlobMetadata> Blobs { get; set; }
}

```

**Comment by julealgon** [comment] 2022-11-25 14:00
Just ran into this exact same problem while converting my orchestrator to isolated in .NET7 as well.

Tried to pass both a tuple with a `Guid` and a `DateTimeOffset`, as well as a custom small model: same results.

Why is it taking so long for this problem to be resolved? It was reported so long ago, and it is such a core scenario for the class-based syntax.

**Comment by jviau** [comment] 2022-11-29 21:46
Fixed via https://github.com/Azure/azure-functions-durable-extension/pull/2330

Will be available in the next preview (which is coming soon).

**Closed by jviau** 2022-11-29 21:46 UTC
Labels: bug
